# Generated by Django 4.2.3 on 2023-07-27 20:26

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckSmsValidity',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_vip',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_telegram_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره تماس اکانت تلگرام'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vip_expiry_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ پایان اشتراک ویژه'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_credit',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='اعتبار حساب'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='عکس پروفایل'),
        ),
    ]
