# Generated by Django 4.2.3 on 2023-07-29 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_delete_checksmsvalidity_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان درخواست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تاریخچه درخواست',
                'verbose_name_plural': 'تاریخچه درخواست ها',
                'ordering': ['-created_at'],
            },
        ),
    ]
