# Generated by Django 4.2.3 on 2023-07-29 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envato', '0008_delete_envatouserfile'),
        ('accounts', '0003_userrequesthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequesthistory',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='envato.envatofile', verbose_name='فایل'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrequesthistory',
            name='is_noticed',
            field=models.BooleanField(default=False, verbose_name='آیا اطلاع رسانی شده است؟'),
        ),
        migrations.AddField(
            model_name='userrequesthistory',
            name='is_single_pay',
            field=models.BooleanField(default=False, verbose_name='آیا پرداخت تکی است؟'),
        ),
    ]
