# Generated by Django 4.2.3 on 2023-08-05 21:11

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userrequesthistory_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vip_expiry_date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 8, 5, 21, 11, 7, 727781), verbose_name='تاریخ پایان اشتراک ویژه'),
        ),
    ]
