# Generated by Django 4.2.3 on 2023-08-11 12:26

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_vip_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vip_expiry_date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 8, 11, 12, 26, 24, 469400), verbose_name='تاریخ پایان اشتراک ویژه'),
        ),
    ]
