# Generated by Django 4.2.3 on 2023-08-11 13:53

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_vip_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allowed_request_per_day',
            field=models.PositiveIntegerField(default=50, verbose_name='اعتبار حساب'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_credit',
            field=models.PositiveIntegerField(default=0, verbose_name='اعتبار حساب'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vip_expiry_date',
            field=django_jalali.db.models.jDateTimeField(default=datetime.datetime(2023, 8, 11, 13, 53, 46, 698073), verbose_name='تاریخ پایان اشتراک ویژه'),
        ),
    ]
