# Generated by Django 4.2.3 on 2023-07-27 10:38

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_time', models.PositiveSmallIntegerField(default=60, verbose_name='زمان توقف ربات بین هر کوئری')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
        migrations.CreateModel(
            name='Envato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=2000, null=True, verbose_name='لینک جزئیات سازمان')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام سازمان')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی')),
            ],
            options={
                'verbose_name': 'شرکت',
                'verbose_name_plural': 'شرکت ها',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EnvatoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='envato.envato', verbose_name='شرکت')),
            ],
            options={
                'verbose_name': 'پروفایل انواتو',
                'verbose_name_plural': 'پروفایل های انواتو',
            },
        ),
    ]
