# Generated by Django 4.2.3 on 2023-07-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configsetting',
            name='envato_cookie',
            field=models.FileField(blank=True, null=True, upload_to='envato', verbose_name='کوکی انواتو'),
        ),
        migrations.AddField(
            model_name='configsetting',
            name='envato_pass',
            field=models.CharField(default=1, max_length=255, verbose_name='پسسورد انواتو'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configsetting',
            name='envato_user',
            field=models.CharField(default=1, max_length=255, verbose_name='نام کاربری انواتو'),
            preserve_default=False,
        ),
    ]
