# Generated by Django 4.2.3 on 2023-07-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envato', '0002_configsetting_envato_cookie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configsetting',
            name='envato_pass',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کلمه عبور انواتو'),
        ),
        migrations.AlterField(
            model_name='configsetting',
            name='envato_user',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام کاربری انواتو'),
        ),
    ]
