# Generated by Django 4.2.3 on 2023-07-27 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('envato', '0003_alter_configsetting_envato_pass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvatoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=2000, verbose_name='لینک فایل')),
                ('file', models.FileField(blank=True, null=True, upload_to='envato-files', verbose_name='فایل')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ و زمان بروزرسانی')),
            ],
            options={
                'verbose_name': 'فایل انواتو',
                'verbose_name_plural': 'فایل های انواتو',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EnvatoUserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envato.envatofile', verbose_name='فایل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ارتباط کابر و فایل',
                'verbose_name_plural': 'ارتباط کاربران و فایل ها',
            },
        ),
        migrations.RemoveField(
            model_name='envatoprofile',
            name='envato',
        ),
        migrations.DeleteModel(
            name='Envato',
        ),
        migrations.DeleteModel(
            name='EnvatoProfile',
        ),
    ]
