# Generated by Django 4.2.3 on 2023-07-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envato', '0005_envatouserfile_is_single_pay_alter_envatofile_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='envatouserfile',
            name='is_noticed',
            field=models.BooleanField(default=False, verbose_name='آیا اطلاع رسانی شده است؟'),
        ),
    ]
