# Generated by Django 4.2.3 on 2023-07-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envato', '0006_envatouserfile_is_noticed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='envatofile',
            old_name='link',
            new_name='page_link',
        ),
        migrations.AddField(
            model_name='envatofile',
            name='src_link',
            field=models.CharField(default=1, max_length=2000, verbose_name='لینک اصلی فایل'),
            preserve_default=False,
        ),
    ]
