# Generated by Django 4.2.3 on 2023-07-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envato', '0007_rename_link_envatofile_page_link_envatofile_src_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnvatoUserFile',
        ),
    ]
