# Generated by Django 4.2.3 on 2023-07-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envato', '0008_delete_envatouserfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='envatofile',
            name='in_progress',
            field=models.BooleanField(default=False, verbose_name='آیا در حال دانلود است؟'),
        ),
    ]
