# Generated by Django 4.2.3 on 2023-07-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envato', '0009_envatofile_in_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ترد فعال',
                'verbose_name_plural': 'ترد های فعال',
            },
        ),
    ]
