# Generated by Django 4.2.3 on 2023-07-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envato', '0010_activethread'),
    ]

    operations = [
        migrations.AddField(
            model_name='configsetting',
            name='envato_queue_number',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='تعداد پردازش صف انواتو'),
        ),
        migrations.AddField(
            model_name='configsetting',
            name='envato_thread_number',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='تعداد پردازش همزمان انواتو'),
        ),
    ]
