# Generated by Django 4.2.3 on 2023-07-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envato', '0011_configsetting_envato_queue_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvatoSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_time', models.PositiveSmallIntegerField(default=5, verbose_name='زمان توقف ربات بین هر کوئری')),
                ('envato_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام کاربری انواتو')),
                ('envato_pass', models.CharField(blank=True, max_length=255, null=True, verbose_name='کلمه عبور انواتو')),
                ('envato_cookie', models.FileField(blank=True, null=True, upload_to='envato', verbose_name='کوکی انواتو')),
                ('envato_thread_number', models.PositiveSmallIntegerField(default=4, verbose_name='تعداد پردازش همزمان انواتو')),
                ('envato_queue_number', models.PositiveSmallIntegerField(default=4, verbose_name='تعداد پردازش صف انواتو')),
            ],
            options={
                'verbose_name': 'تنظیمات انواتو',
                'verbose_name_plural': 'تنظیمات انواتو',
            },
        ),
        migrations.DeleteModel(
            name='ConfigSetting',
        ),
    ]
