# Generated by Django 4.2.3 on 2023-07-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envato', '0012_envatosetting_delete_configsetting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActiveThread',
            new_name='EnvatoActiveThread',
        ),
        migrations.AlterModelOptions(
            name='envatoactivethread',
            options={'verbose_name': 'ترد فعال انواتو', 'verbose_name_plural': 'ترد های فعال انواتو'},
        ),
    ]
