# Generated by Django 4.2.3 on 2023-07-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envato', '0013_rename_activethread_envatoactivethread_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='envatosetting',
            name='login_status',
            field=models.BooleanField(default=False, verbose_name='آیا احراز هویت فعال است؟'),
        ),
    ]
