# Generated by Django 4.2.3 on 2023-07-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envato', '0014_envatosetting_login_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envatofile',
            name='src_link',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='لینک اصلی فایل'),
        ),
    ]
