# Generated by Django 4.2.3 on 2023-07-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envato', '0015_alter_envatofile_src_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envatofile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='فایل'),
        ),
    ]
