# Generated by Django 4.2.3 on 2023-07-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envato', '0016_alter_envatofile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envatofile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='envato/', verbose_name='فایل'),
        ),
    ]
