# Generated by Django 4.2.3 on 2023-08-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envato', '0017_alter_envatofile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='envatofile',
            name='is_acceptable_file',
            field=models.BooleanField(default=True, verbose_name='آیا فایل با فرمت های طراحی شده سازگار است؟'),
        ),
    ]
