# Generated by Django 4.2.3 on 2023-08-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envato', '0018_envatofile_is_acceptable_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvatoTelegramBotSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_address', models.CharField(max_length=255, verbose_name='آدرس')),
                ('bot_token', models.CharField(max_length=255, verbose_name='توکن')),
            ],
            options={
                'verbose_name': 'تنظیمات ربات تلگرام انواتو',
                'verbose_name_plural': 'تنظیمات ربات تلگرام انواتو',
            },
        ),
        migrations.AlterField(
            model_name='envatofile',
            name='page_link',
            field=models.CharField(max_length=5000, verbose_name='لینک صفحه اصلی فایل'),
        ),
        migrations.AlterField(
            model_name='envatofile',
            name='src_link',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='لینک اصلی فایل'),
        ),
    ]
